<<: !include secrets.yaml

esphome:
  name: ufh-lounge
  platform: esp8266
  board: nodemcu

# Enable logging
logger:
  level: DEBUG

captive_portal:

sensor:
  - platform: ntc
    id: temp_lounge_floor
    sensor: resistance_sensor
    name: "Lounge - Floor Temperature"
    calibration:
      - 9.863kOhm -> 23.6째C
      - 7.130kOhm -> 30.4째C
      - 15.300kOhm -> 13.4째C
      #b_constant: 3950
      #reference_temperature: 25째C
      #reference_resistance: 10kOhm

    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5
  - platform: resistance
    id: resistance_sensor
    sensor: source_sensor
    configuration: UPSTREAM
    resistor: 5.1kOhm
    name: Resistance Sensor
  - platform: adc
    pin: A0
    id: source_sensor
    update_interval: never
    filters:
      - multiply: 3.3

switch:
  - platform: gpio
    pin: D0
    id: ntc_vcc

interval:
  - interval: 10s
    then:
      - switch.turn_on: ntc_vcc
      - component.update: source_sensor
      - switch.turn_off: ntc_vcc
